{{- define "common.fullname" -}}
{{- .Chart.Name }}-{{ .Release.Name }}
{{- end }}

{{- define "service.controller" -}}
{{- include "common.fullname" . }}-controller
{{- end }}

{{- define "service.http" -}}
{{- include "common.fullname" . }}-http
{{- end }}

{{- define "sidecar.exporter" -}}
{{- $certPath := "/root/.chia" }}
{{- if ne "chia" . }}
  {{- $certPath = (printf "/root/.chia/%s" . ) -}}
{{- end }}
- name: metrics-exporter
  image: {{ default "nold360/chia-fork-exporter:latest" }}
  args:
    - -fork
    - {{ . }}
    - -cert
    - {{ $certPath }}/mainnet/config/ssl/full_node/private_full_node.crt
    - -key
    - {{ $certPath }}/mainnet/config/ssl/full_node/private_full_node.key
  volumeMounts:
  - name: config
    mountPath: /root/.chia
  ports:
  - name: metrics
    containerPort: 9133
{{- end }}
