{{- range $.Values.worker }}
---
{{- $volumes := $.Values.persistence }}
{{- if .persistence }}
  {{- $volumes := .persistence }}
  {{- $_ := deepCopy $.Values.persistence | merge $volumes }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
    app.kubernetes.io/instance: {{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  revisionHistoryLimit: 3
  updateStrategy:
    type: {{ .updateStrategy | default "OnDelete" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
      app.kubernetes.io/instance: {{ .name }}
  serviceName: {{ include "common.fullname" $ }}-{{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
        app.kubernetes.io/instance: {{ .name }}
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: {{ include "common.fullname" $ }}-{{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy | default "Always" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /mnemonic/mnemonic.txt /root/.chia/mnemonic.txt
          env:
            - name: blockchains
              value: {{ .blockchains | default .name }}
            - name: controller_api_port
              value: {{ $.Values.machinaris.service.controllerPort | default 8927 | quote }}
            - name: controller_host
            {{- if eq $.Values.machinaris.controller .name }}
              value: localhost
            - name: worker_address
              value: 127.0.0.1
            {{- else}}
              value: {{ include "service.controller" $ | quote }}
            - name: worker_address
              value: {{ include "common.fullname" $ }}-{{ .name }}-api
            {{- end }}
            - name: worker_api_port
              value: {{ .service.port | quote }}
            - name: plots_dir
              value: {{ $volumes.plots.mountPath }}
            {{- toYaml $.Values.env | default list | nindent 12 }}
          ports:
            - name: api
              containerPort: {{ .service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /root/.chia
          {{- if $volumes.plots }}
            - name: plots
              mountPath: {{ $volumes.plots.mountPath }}
          {{- end }}
          {{- if $volumes.temp }}
            - name: plotting
              mountPath: {{ $volumes.temp.mountPath }}
          {{- end }}
          {{- if $.Values.mnemonic }}
            - name: mnemonic
              mountPath: /mnemonic
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .service.port }}
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8926
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8926
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          ports:
          - containerPort: {{ .service.port }}
            name: api
          {{- if eq $.Values.machinaris.controller .name }}
          - containerPort: {{ $.Values.machinaris.service.httpPort }}
            name: http
          {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" $ }}-{{ .name }}
        {{- if $volumes.plots }}
        - name: plots
          hostPath: 
            path: {{ $volumes.plots.path }}
        {{- end }}
        {{- if $volumes.temp }}
        - name: plotting
          hostPath: 
            path: {{ $volumes.temp.path }}
        {{- end }}
        {{- if $.Values.mnemonic }}
        - name: mnemonic
          secret:
            secretName: mnemonic
            items:
              - key: mnemonic.txt
                path: mnemonic.txt
        {{- end }}
  volumeClaimTemplates:
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}-api
spec:
  type: {{ .service.type | default "ClusterIP" }}
  ports:
  - port: {{ .service.port }}
    targetPort: api
    protocol: TCP
    name: api
  selector:
    app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
    app.kubernetes.io/instance: {{ .name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
spec:
  accessModes:
    - {{ $.Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.persistence.config.size | quote }}
  storageClassName: {{ $.Values.persistence.config.storageClass | quote }}

{{- if eq $.Values.machinaris.controller .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.controller" $ }}
spec:
  type: {{ $.Values.machinaris.service.type | default "ClusterIP" }}
  ports:
  - port: {{ $.Values.machinaris.service.controllerPort | default 8927 }}
    targetPort: api
    protocol: TCP
    name: api
  selector:
    app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
    app.kubernetes.io/instance: {{ .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.http" $ }}
spec:
  type: {{ $.Values.machinaris.service.type | default "ClusterIP" }}
  ports:
  - port: {{ $.Values.machinaris.service.httpPort | default 8926 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "common.fullname" $ }}-{{ .name }}
    app.kubernetes.io/instance: {{ .name }}
{{- end }}
{{- end }}
